### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lstmemery** [rtwillett/YeastGenomics_shiny#1]
Hey there, I'm with a bioinformatics hackathon group working on the same dataset. We really like what you did here and would like to extend this work. If that works for you, could you add a LICENSE file to this repo? 

A good open default would be MIT, but you can read more about licenses here.

https://help.github.com/en/articles/licensing-a-repository

Thank you for your consideration!

**Comment by rtwillett** [comment]
Sorry that I'm taking so long to get back to you about this. I've been buried in other personal projects in addition to my work. 

The license has been applied. Happy hacking to you and anyone else.
